env: ${ENV}
apiPort: ${API_PORT}
frontendURL: ${FRONTEND_URL}
jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
  accessTTLMinutes: ${JWT_ACCESS_TTL_MINUTES}
database:
  postgresDSN: ${DB_WRITE_DSN}
admin:
  name: ${ADMIN_NAME}
  cpf: ${ADMIN_CPF}
  password: ${ADMIN_PASSWORD}
  email: ${ADMIN_EMAIL}
  phone: ${ADMIN_PHONE}
  markupPercent: ${ADMIN_MARKUP_PERCENT}
  machineFeePercent: ${ADMIN_MACHINE_FEE_PERCENT}
  installmentFeePercent: ${ADMIN_INSTALLMENT_FEE_PERCENT}
